# Generated by Django 6.0.7 on 2026-07-28 20:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ebook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('original_title', models.CharField(blank=True, max_length=255)),
                ('synopsis', models.TextField()),
                ('language', models.CharField(max_length=255)),
                ('release_date', models.SmallIntegerField(blank=True, null=True)),
                ('image_url', models.URLField()),
                ('magnetic_link', models.CharField(max_length=2048)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('legal_basis', models.CharField(choices=[('PRAZO_POS_MORTE_AUTOR', 'Prazo pós morte do autor'), ('PRAZO_DESDE_DIVULGACAO', 'Prazo após o lançamento de um filme'), ('AUTOR_DESCONHECIDO', 'Autor desconhecido, portanto não pode reivindicar os direitos autorais'), ('RENUNCIA_DIREITOS', 'Autor renunciou aos direitos autorais da obra'), ('OUTRO', 'Outro motivo que não se enquadra nos anteriores')], max_length=255)),
                ('observation_check', models.TextField(blank=True)),
                ('pages_number', models.PositiveSmallIntegerField()),
                ('authors', models.ManyToManyField(to='catalog.author')),
                ('genres', models.ManyToManyField(to='catalog.genre')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
